### PR TITLE
Switch to TorchVision

### PR DESCRIPTION
**Pull request by bushshrub**
As seen in #22, using torchvision's transformations produces better edges as compared to the original solution.

Unfortunately I am not able to test the ODS score with the repo you linked, but just from my untrained eyeballs it appears to be better. Will post more metrics later.

### CODE REVIEW

**Comment by sniklaus** [comment]
Thanks for working on this!

I am afraid that `torchvision.transforms.ToTensor()(PIL.Image.open(arguments_strIn))` is incorrect though, since it will provide the input image in RGB order but the pre-trained model expects BGR order instead (see `[:,:,::-1]` at [1]).

[1] https://github.com/s9xie/hed/blob/master/examples/hed/HED-tutorial.ipynb

**Comment by xiurobert** [comment]
Gotcha. Perhaps the `[:,:,::-1]` to invert RGB to BGR can be applied directly to the ToTensor() call?

**Comment by sniklaus** [comment]
Yeah, you could change the order to make it properly work - but then why change the code in the first place? Is there a benefit from using `torchvision.transforms.ToTensor` over the manual way (I don't know but I am curious)?

**Comment by xiurobert** [comment]
Looks like the manual method actually caused some rounding errors. The ToTensor transform avoids these rounding errors.

**Comment by xiurobert** [comment]
Interesting. I tested my result with flip (to convert it properly this time) but I found rounding errors. Not sure why. I'll see if I have time to investigate this further.

**Comment by sniklaus** [comment]
Maybe I am reading this wrong, but your pull request was using `torchvision.transforms.ToTensor()(PIL.Image.open(...))` and the `ToTensor()` calls the functional `to_tensor()` that I linked above (and not the `pil_to_tensor`): https://github.com/pytorch/vision/blob/ea197e4e58157f8be4ef3ed1caf5b707febe5437/torchvision/transforms/transforms.py#L135

Anyways, let me know if you find anything during your investigations - thanks!

**Comment by xiurobert** [comment]
Looks like I made a typo.

**Pull request closed without merging**
